cmake_minimum_required(VERSION 3.20)

project(PhysX)

set(PX_BUILDSNIPPETS OFF)
set(PX_BUILDPVDRUNTIME OFF)
set(PX_GENERATE_STATIC_LIBRARIES ON)
set(PX_FLOAT_POINT_PRECISE_MATH OFF)
set(NV_USE_STATIC_WINCRT OFF)
set(NV_USE_DEBUG_WINCRT OFF)
set(PHYSX_ROOT_DIR ${CMAKE_CURRENT_SOURCE_DIR}/physx)
set(PX_OUTPUT_LIB_DIR ${CMAKE_CURRENT_BINARY_DIR}/PhysX/lib)
set(PX_OUTPUT_BIN_DIR ${CMAKE_CURRENT_BINARY_DIR}/PhysX/bin)

set(TARGET_BUILD_PLATFORM windows)
set(PUBLIC_RELEASE OFF)
if (NOT WIN32)
    set(TARGET_BUILD_PLATFORM linux)
endif()


set(PX_SCALAR_MATH OFF)
# PhysX SIMD support is not correct under MacOSX
if (APPLE OR ${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
    message(STATUS "PhysX: disable SIMD")
    set(PX_SCALAR_MATH ON)
endif()
add_subdirectory(physx/compiler/public)